site_name: Cook Book

theme:
    name: "material"

nav:
    - Home: index.md
    - Recipes:
        - apple_cake/index.md
        - nasi_goreng/index.md
    - Tags: tags.md

plugins:
  - search
  - tags:
      tags_file: tags.md
