site_name: Cook Book

theme:
    name: "material"
    features:
        - search.suggest
        - search.highlight
        - navigation.indexes
    language: en

nav:
    - Recipes:
        - index.md
        - apple_cake/index.md
        - nasi_goreng/index.md
        - dal/index.md
        - gnocchi_with_pesto_and_pistachios/index.md
        - salami_cake/index.md
        - yogurt_granola_jar/index.md
    - Tags: tags.md

plugins:
  - search
  - tags:
      tags_file: tags.md
