site_name: Cook Book
site_url: https://gr8jam.github.io/cook-book/

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - navigation.indexes
  language: en

nav:
  - Gallery: index.md
  - tags.md
  - todo.md

plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true